//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobsearch
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int App_Id { get; set; }
        public int User_Id { get; set; }
        public int Job_Id { get; set; }
        public string resume { get; set; }
        public int comp_Id { get; set; }
        public System.DateTime Appdate { get; set; }
    }
}
